id: 6b7cc9304415483c859e19e890139dd4
initial_creation_type: ebook
created_at: 8/04/2021
last_modified_at: 25/11/2021
source_metadata:
  title: test
  subtitle: ''
  authors:
  - test
  collection: ''
  publisher: ''
  id: test
  cover: tmpeunx17s8.jpg
  credit: tmpf1q_1iie.jpg
